version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      -
  app:
    image: event-logger-spring-boot:latest
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        - db
    ports:
      - '8080:8080'
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: example