version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - '3307:3307'
