CREATE TABLE IF NOT EXISTS events (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    time TIMESTAMP NOT NULL,
    type ENUM ('DEBUG', 'INFO', 'WARNING', 'ERROR') NOT NULL,
    message VARCHAR(1024) NOT NULL,
    userId VARCHAR(30) NOT NULL,
    transactionId VARCHAR(30) NOT NULL
);